name: Update VERSIONING.md on Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-versioning:
    # don’t run when github-actions[bot] pushes
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Update VERSIONING.md & commit as bot
        shell: bash
        run: |
          # 1. Prepare variables
          FULL_SHA="${GITHUB_SHA}"
          SHORT_SHA="${FULL_SHA:0:7}"
          ACTOR="@${GITHUB_ACTOR}"

          # 2. In-place replace both placeholders with Perl
          perl -pe '
            s/\$\{\{\s*steps\.extract_sha\.outputs\.short_sha\s*\}\}/'"${SHORT_SHA}"'/g;
            s/@\$\{\{\s*github\.actor\s*\}\}/'"${ACTOR}"'/g;
          ' -i src/VERSIONING.md

          # 3. Commit & push if something changed
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes in VERSIONING.md - nothing to commit"
          else
            git add src/VERSIONING.md
            git commit -m "chore: update VERSIONING.md placeholders"
            git push
          fi
