name: Update VERSIONING.md on Push

on:
  push:
    branches:
      - main

permissions:
  contents: write   # needed to commit back

jobs:
  update-versioning:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Extract short SHA
        id: extract_sha
        run: |
          full_sha="${{ github.sha }}"
          echo "short_sha=${full_sha:0:7}" >> $GITHUB_OUTPUT

      - name: Replace SHA placeholder
        uses: richardrigutins/replace-in-files@v2
        with:
          files: src/VERSIONING.md
          search-text: '\${{ steps.extract_sha.outputs.short_sha }}'
          replacement-text: ${{ steps.extract_sha.outputs.short_sha }}  # evaluated by GHA

      - name: Replace actor placeholder
        uses: richardrigutins/replace-in-files@v2
        with:
          files: src/VERSIONING.md
          search-text: '@\${{ github.actor }}'
          replacement-text: '@${{ github.actor }}'

      - name: Commit & push as GitHub Actions bot
        uses: EndBug/add-and-commit@v7
        with:
          add: 'src/VERSIONING.md'
          message: 'chore: update VERSIONING.md placeholders'
          default_author: github_actions
