# .github/workflows/update-versioning.yml
name: Update VERSIONING.md on Push

on:
  push:
    branches:
      - main

jobs:
  update-versioning:
    # Skip if this push was done by the GitHub Actions bot
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 1. Extract the short SHA
      - name: Extract short SHA
        id: extract_sha
        shell: bash
        run: |
          full_sha="${{ github.sha }}"
          short_sha="${full_sha:0:7}"
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT

      # 2. Capture the committer login
      - name: Set actor env var
        run: echo "ACTOR=${{ github.actor }}" >> $GITHUB_ENV

      # 3. Replace placeholders in src/VERSIONING.md
      - name: Replace variables in VERSIONING.md
        shell: bash
        run: |
          SHA="${{ steps.extract_sha.outputs.short_sha }}"
          ACTOR="${{ env.ACTOR }}"
          sed -i \
            -e "s|\${{ steps.extract_sha.outputs.short_sha }}|${SHA}|g" \
            -e "s|@\${{ github.actor }}|@${ACTOR}|g" \
            src/VERSIONING.md

      # 4. Commit & push changes if any
      - name: Commit & push changes
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/VERSIONING.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: update VERSIONING.md placeholders"
            git push
          else
            echo "No changes to commit"
          fi
