name: Update VERSIONING.md on Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-versioning:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Update VERSIONING.md & commit as bot
        shell: bash
        run: |
          FULL_SHA="${GITHUB_SHA}"
          SHORT_SHA="${FULL_SHA:0:7}"
          ACTOR="${GITHUB_ACTOR}"

          perl -i -pe '
            # 1) Replace (optional escaped) short-SHA token
            s/\\?\$\{\{\s*steps\.extract_sha\.outputs\.short_sha\s*\}\}/'"${SHORT_SHA}"'/g;
            # 2) Replace (optional escaped) full-SHA token
            s/\\?\$\{\{\s*github\.sha\s*\}\}/'"${FULL_SHA}"'/g;
            # 3) Replace actor token
            s/\$\{\{\s*github\.actor\s*\}\}/'"${ACTOR}"'/g;
          ' src/VERSIONING.md

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes to VERSIONING.md"
          else
            git add src/VERSIONING.md
            git commit -m "update VERSIONING.md placeholders"
            git push
          fi
